.travis.yml, package.json, scripts/check_gm.sh
=> chore(install): check that `gm` is installed

lib/db/index.js, lib/db/memory.js, lib/db/mysql.js, lib/img/aws.js, lib/img/local.js, lib/routes/avatar/delete.js, lib/server/worker.js, test/api.js, test/lib/mock.js, test/lib/server.js
=> feat(images): delete images from s3 when asked to

test/load/avatar/avatar.js, test/load/avatar/load.js
This deletes the image after initial upload and successful download. @seanmonstar or @rfk r?
=> feat(test): in load test, add delete after download

test/load/avatar/avatar.js
a couple of test fixes
- expecting new dowloaded default size
- set maxSockets (did this change in `request`, or did I just have this wrong? </rhetorical>)
@seanmonstar r?
=> a couple of test fixes

lib/db/mysql/index.js, lib/db/mysql/patch.js, lib/db/mysql/patches/patch-000-001.sql, lib/db/mysql/patches/patch-001-000.sql, lib/db/mysql/patches/patch-001-002.sql, lib/db/mysql/patches/patch-002-001.sql, lib/db/mysql/schema.sql, npm-shrinkwrap.json, package.json
=> feat(mysql): use mysql patcher to allow incremental schema updates

lib/routes/profile.js, test/api.js
=> feat(profile): add etag to profile API endpoint

lib/config.js, npm-shrinkwrap.json, package.json
=> chore(config): Update convict and switch on strict validation.

.eslintrc, lib/db/mysql/index.js, npm-shrinkwrap.json, package.json
Per https://github.com/mozilla/fxa-profile-server/pull/119/files#r32651870 conversation
=> chore(build): Tweak ESLint config to disable global consistent-this rule

lib/routes/display_name/post.js, test/api.js
We should probably allow users to clear their display name.
@vladikoff r?
=> fix(display_name): allow a blank display name

package.json
=> chore(package): remove main from package.json

lib/batch.js, lib/error.js, lib/routes/email.js, npm-shrinkwrap.json, test/api.js, test/lib/mock.js
Closes #121
@zaach interested in r?
=> fix(server): return errno 104 if oauth server is drunk

npm-shrinkwrap.json, package.json
=> fix(run_dev): add rimraf dependency back

docs/API.md, lib/batch.js, lib/routes/display_name/get.js, test/api.js, test/lib/mock.js
=> Return 204 if user does not have a display name set

npm-shrinkwrap.json
=> chore(dependencies): update mozlog to 2.0.2

lib/server/web.js, test/api.js, test/lib/mock.js
=> fix(server): prevent null exception when oauth server is down

lib/config.js, lib/routes/avatar/upload.js, lib/server/worker.js, test/api.js, test/events.js, test/lib/mock.js
=> fix(avatars): add configuration to adjust avatar upload size

lib/compute/image-cc.js, lib/config.js
=> fix(avatars): graphicsmagick processing limits

Gruntfile.js
See more details in https://github.com/mozilla/fxa-profile-server/issues/161
=> fix(build): remove shrinkwrap validate

lib/request.js
=> fix(server): set nodejs/request maxSockets to Infinity

lib/img-workers.js
=> fix(worker): disable gzip encoding on requests to local worker

.travis.yml, npm-shrinkwrap.json, package.json, tasks/nsp.js
=> fix(build): add grunt-nsp

lib/config.js
=> fix(config): adjust lib gm limits for aws

lib/db/mysql/index.js
=> fix(mysql): fix patcher version check to enforce patch >= n

lib/config.js, lib/error.js, lib/routes/email.js, lib/server/web.js, npm-shrinkwrap.json, package.json, test/api.js, test/lib/mock.js
=> feat(email): fetch email from auth-server /account/profile

lib/config.js, lib/error.js, lib/routes/email.js, lib/server/web.js, npm-shrinkwrap.json, package.json, test/api.js, test/lib/mock.js
Reverts mozilla/fxa-profile-server#166
=> revert(email): fetch email from auth-server /account/profile

docs/API.md, lib/routes/email.js, lib/routes/profile.js, test/api.js
=> feat(openid): make /v1/profile act as the OIDC UserInfo endpoint

lib/routes/lbheartbeat.js, lib/routing.js, test/server.js
Needed for [Dockerflow](https://github.com/mozilla-services/Dockerflow#containerized-app-requirements)
=> feat(docker): Add /__lbheartbeat__ endpoint for Dockerflow compatibility

scripts/run_dev.js
=> fix(dev): stop all child servers if one crashes

lib/config.js, lib/env.js, lib/server/web.js
Paired with https://github.com/mozilla-services/puppet-config/pull/2179. 
r? - @jbuck
=> revert changes for NODE_ENV=production

test/api.js
=> fix(tests): fix docker racing tests

config/dev.json, docs/API.md, lib/config.js, lib/customs.js, lib/error.js, lib/pool.js, lib/routes/avatar/post.js, lib/server/web.js, npm-shrinkwrap.json, package.json, test/customs.js
=> feat(customs): limit avatar uploads

.travis.yml
=> fix(travis): build on node 4 and 6

bin/server.js
This is already shown in dev mode at log level debug. But this will show it when not at debug.
=> fix(config): log config at info level at startup

lib/events.js
=> fix(avatars): only delete avatars if avatars set

bin/_static.js, config/dev.json, lib/config.js, lib/env.js, lib/img/local.js, lib/server/web.js, scripts/run_dev.js
@mozilla/fxa-devs r?
Related to https://github.com/mozilla/fxa/issues/57
=> fix(config): make NODE_ENV consistent across servers

lib/routes/root.js
refs: bug 1320217
similar to: mozilla/fxa-content-server#4804
Fix commend execution in the unlikely event the application is run from a location with a malicious or malformed directory name per rfk's suggestions in the bug mentioned above.
Functional Tests:
```
fxa-local-dev/fxa-profile-server - [master] » curl -X GET http://localhost:1111/__version__
{
"version": "1.82.1",
"commit": "usage:git [--version] [--help] [-C <path>] [-c name=value]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: …
```
=> fix(version): use cwd and env var to get version

lib/config.js, lib/routes/avatar/delete.js, lib/routes/avatar/post.js, lib/routes/avatar/upload.js, lib/routes/display_name/post.js, lib/sqs.js, lib/updates-queue.js
Connects to https://github.com/mozilla/fxa-features/issues/118
=> feat(push): notify the auth-server when profile updated

circle.yml
Circle CI should be pushing to docker hub with the circle branch as the tag and not 'latest'
=> Push to dockerhub with the circle branch

lib/routes/profile.js
fixes https://github.com/mozilla/fxa-profile-server/issues/255
cc; @vladikoff Tests are still o.O
=> chore(logs): add logging around caching profile

CHANGELOG.md, lib/config.js, npm-shrinkwrap.json, package.json
=> Train 90 uplift

lib/routes/profile.js, lib/server/web.js
Fix  ```/upload and /display_name fail (for a non-moz, etc.) email```
=> fix(cache):register server method on server creation

lib/routes/display_name/post.js, test/api.js
Fixes https://github.com/mozilla/fxa-profile-server/issues/261
cc: @vladikoff
=> fix(displayName): length validation in post

package.json
Update to latest major version. r? - @seanmonstar
=> fix(newrelic): update to v2.1.0

.nsprc, lib/compute/image-cc.js, npm-shrinkwrap.json, package.json
Fixes #287; @mozilla/fxa-devs r?
=> chore(nsp): nsp updates

lib/compute/image-cc.js
=> fix(logging): Don't log raw numbers as log msg.

npm-shrinkwrap.json, package.json
=> chore(deps): update deps, fix nsp

test/api.js
Fixes #203 : Added  mocks for the log to not output the summary of a 500 for the successful tests.
=> fix(traceback): #203 add mock

CHANGELOG.md, Dockerfile-build, npm-shrinkwrap.json, package.json
=> chore(merge): Merge train 114 into master

npm-shrinkwrap.json, package.json, test/mysql.js
=> fix(deps): update to latest Sinon

.nsprc, npm-shrinkwrap.json
=> fix(audit): rewrap deps to fix security warnings

npm-shrinkwrap.json, package.json
Connects to https://github.com/mozilla/fxa/issues/325
=> fix(npm): update to latest npmshrink

npm-shrinkwrap.json, package.json
@mozilla/fxa-devs - r?
There is no train-129 tag yet, so I'll make one once this lands.
=> chore(deps): Update Hapi
