mozilla/fxa-profile-server

docs/API.md

I noticed while working on https://github.com/mozilla/PyFxA/pull/15 that the `/v1/profile` endpoint returns an "avatar" field, but this isn't shown in the example in docs.

fix(docs): note "avatar" field in /v1/profile response

---

docs/API.md
lib/compute/image-cc.js
lib/compute/index.js
lib/config.js
lib/img/index.js
lib/server/worker.js
test/api.js
test/lib/mock.js

When an avatar is uploaded, we will now generate multiple sizes of the
image, to better accommodate various environments that the avatar may
appear.
The sizes generated are based of current constants in the `lib/img/index.js`
module. The `SIZES` constant contains a map of `suffix` to `height/width`
values. The suffix `default` is special cased, and will actually mean no
suffix. Every other value will be appended on the end of the URL, with an
underscore.
The current `SIZES` are:
{
small: { h: 100, w: 100 },
default: { h: 200, w: 200 },
large: { h 600, w: 600 }
}
which generate 3 images when an upload occurs:
- https://s3.url/<imageid>_small (100px x 100px)
- https://s3.url/<imageid> (200px x 200px)
- https://s3.url/<imageid>_large (600px x 600px)
Closes #68
Closes #89

feat(avatar): add multiple image support

---

CHANGELOG.md
package.json

Noticed this a while back but assumed this was some hand-editing mistake. Turns out the `repository` value in `package.json` is not per npmjs.org standard, and `conventional-changelog` spits out a url that cannot be loaded. 
So this just fixes the package.json, and corrects all the prior changelog entries to have valid URLs.

fix(changelog): set package.json repository correctly so conventional-changelog creates valid URL

---

.travis.yml

This adds `'iojs` and `nodejs 0.12` to the travis runs. I don't expect we'll be moving from `0.10` soon, but since they currently pass, we should probably lock that in, and if we have failures that are due to upstream, we can feed that information back to the respective upstream repositories. 
This is kind of a meta-PR to see if folks agree there is value in doing this at this point. It does add some overhead to tests, and possible flakiness, but I think as {node,io}.js users we should do this.

chore(travis): also build/test on iojs and nodejs 0.12

---

lib/batch.js
lib/db/index.js
lib/routes/profile.js
test/api.js

So basically, using Hapi's `server.inject()`, the `/profile` endpoint just clumps together the results of requests to each lesser piece of information. Any 403s (scope not allowed) and 404s (such as has no avatar) simply means that value isn't in the returned result.
Closes #108

feat(profile): return all /profile pieces that scopes allow

---

package.json

specifying the type and URL is deprecated:
https://docs.npmjs.com/files/package.json#license

chore(license): Update license to be SPDX complaint

---

lib/routes/avatar/get.js
test/api.js

Related to #111. We still have to figure out how to use these etags.

feat(avatar): Add etag to the profile avatar API endpoint

---

.travis.yml

We should use npm@2 since the default with nodejs 0.10 is an obsolete and flaky version of npm (1.4.28). We already build production with npm@2.6.1; I'm not particularly concerned with what version travis uses as long as it in the 2.x series.
r? - @seanmonstar - note no need to merge this before train-42 is cut.

chore(travis): use npm@2 for more stable installs

---

lib/config.js

I assume you meant to add these options. Merging when travis passes because latest.dev.lcip.org is currently broken.

fix(config): add options events.region and events.queueUrl

---

lib/routes/display_name/post.js
test/api.js

Fixes #126.
I went with a very slim list of control characters that IMHO have no business being in a display name, and would only be there to cause trouble.  I also added tests that various other unicodey things are accepted without trouble, which seemed to work except for one issue with JSON.parse-ing the result payload in the tests.
@seanmonstar r?

fix(display_name): Don't allow control characters in the display_name field

---

lib/routes/root.js
lib/routing.js
test/server.js

Fixes #134. This preserves the `/` route but extends the output to include the git source repo, and adds an alternate route `/__version__` that serves the same content and a couple of more tests of the output. 
So content used to look like
```
{
"version": "0.44.0",
"commit": "e31f764c6dcfaeecc8e0ac531002eeab279137ea"
}
```
and is now like:
```
{
"version": "0.44.0",
"commit": "e31f764c6dcfaeecc8e0ac531002eeab279137ea",
"source": "git://github.com/mozilla/fxa-profile-server.git"
}
```

chore(version): add /__version__ route with source repo

---

lib/routes/root.js

Apologies for futzing with this. 
I realized that git-config should use an explicit path to the config location (because, on fxa-dev boxes, fxa-oauth-server starts from `/`, not the checked out repo, and so can't find the config). 
Also, eliminated and unused IFFE, and added a newline to the output because nicer.

fix(version): use explicit path with git-config

---

bin/_static.js
bin/server.js

Just cleaning up deprecation warnings in logs. r? - @seanmonstar

chore(convict): use .getProperties(), not deprecated .root()

---

lib/db/mysql/index.js
package.json
test/mysql.js

This was an idea I had to enforce mysql strict mode and utf8mb4 on all db connections.  It's possible (and advisable!) to set these defaults in the MySQL server itself, but we can also enforce them here as an additional layer of protection.
No tests yet, because we don't have any test infra for mocking out MySQL in this repo.
@jrgm @vladikoff thoughts?

feat(mysql): Ensure db connections always run in strict mode.

---

lib/server/web.js
test/server.js

Same changes as: https://github.com/mozilla/fxa-oauth-server/pull/437
Add security headers (see also the commit messages).
I'm assuming these API endpoints aren't iframed anywhere.
We discussed having the webserver send these, but having this in code allows it to be tested and makes dev and prod environments more similar. Both of those things make @jrgm happy (per https://github.com/mozilla-services/cloudops-deployment/pull/334#issuecomment-270717289).

Add security headers

---

lib/server/web.js
test/api.js
test/events.js
test/lib/util.js
test/server.js

r? - @seanmonstar, @g-k 
Discussion here: https://github.com/mozilla-services/cloudops-deployment/pull/334#issuecomment-272351058, and particularly here: https://github.com/mozilla-services/cloudops-deployment/pull/334#issuecomment-272502735, which I won't repeat here.

fix(headers): add cache-control headers to api endpoints

---

test/server.js

Follow up to https://github.com/mozilla/fxa-profile-server/pull/231. Just a small test refactor to use the same header checks consistently.
r? - @seanmonstar

refactor(headers): re-use same header checks for all tests

---

lib/config.js

Maybe this needs an overally cleanup, but right now, this unblocks overriding of the `img.uploads.dest.public` config when using local image driver.
r? - @seanmonstar

fix(config): only force this settting if it's the default value

---

bin/server.js

If we've failed the LISTEN, don't report "listening". Exit.
r? - @seanmonstar

fix(startup): exit if server.start() returns an error

---

lib/compute/image-cc.js
test/api.js
test/lib/mock.js

Fixes for #309 Clean up 'Buffer' calls to deprecated API

fix(buffer): #309 Clean up 'Buffer' calls to deprecated API

---

lib/server/web.js
package.json

This is to help @deeptibaghel with #334. I added a ton of logging to Deepti's PR and Hapi and noticed that a route's `scope` value was being updated for every test suite, the next test suite would then use the implicant values from the previous suite as it's scopes.
This makes a copy of the route definition which is safe to mutate. Still a WIP because I would expect tests to be failing on master too, and I'm not sure why they aren't.
cc @rfk, @vladikoff, @deeptibaghel

fix(test): Avoid cross test pollution caused by mutating route objects.

---

lib/config.js
lib/events.js

Folks,
First of all, quite new to all this collaboration bits and bobs. I'm trying to run my own Mozilla Services. For my simple setup I don't see the need to have config.events to be set. When I change the NODE_ENV variable to production it requires me though. 
According to the friendly folks in #fxa it's made deliberately hard to disable the events system to guard against accidentally deploying this into production without it being properly set. It was reasonable to create a configuration flag to disable this requirement which is by default set to true. 
So hereby.
Best regards,
Jurgen Brunink

Add option to disable requirement of config.events to be set in production

---

lib/img-workers.js
test/api.js
test/lib/mock.js

Fixes #392?
Not sure if I've done the right thing here or not, because I couldn't see how to make the test respond with an array (or just an object with numeric keys). I know I'm looking in `test/lib/mock.js`, but I got lost trying to follow the request/response path. So probably this needs more work before it's ok to merge, if so some tips on testing would be appreciated.
I *think* I'm changing the correct log message based on the description in the issue though.
@mozilla/fxa-devs r?/help?

fix(logs): unwrap nested errors in img-worker log
